/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Session;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Wazil Razeen
 */
public class ManageSession extends javax.swing.JFrame {

    /**
     * Creates new form ManageSession
     */
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    
    
    public ManageSession() {
        initComponents();
        showTable3();
        combo1();
        combo2();
        combo3();
        combo4();
        combo5();
        clear();
    } 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBack3 = new javax.swing.JButton();
        btnHome3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        slecture = new javax.swing.JComboBox<>();
        stags = new javax.swing.JComboBox<>();
        sscode = new javax.swing.JComboBox<>();
        ssubject = new javax.swing.JComboBox<>();
        sgroup = new javax.swing.JComboBox<>();
        dhrs = new javax.swing.JTextField();
        nostudents = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnViewSession = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 4));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 4));

        btnBack3.setText("B");
        btnBack3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        btnHome3.setText("H");
        btnHome3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setText("ABC INSTITUTE");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setText("TIMETABLE MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(89, 89, 89))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage Session");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Time Table Generator");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        sessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "sessionId", "Select Lecturer", "Select Tags", "Select Subject Code", "Select Subject", "Select Group", "Duration (Hrs)", "Number of Dtudents"
            }
        ));
        sessionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sessionTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sessionTable);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Lecturer");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Select Tag");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Select Subject Code");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Select Subject");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Select Group");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Duration (Hrs)");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Number of Students");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        slecture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Lecturer" }));
        slecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slectureActionPerformed(evt);
            }
        });

        stags.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Tags" }));

        sscode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject Code" }));

        ssubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));

        sgroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Group" }));

        nostudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nostudentsActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(51, 255, 51));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnViewSession.setBackground(new java.awt.Color(51, 102, 255));
        btnViewSession.setText("View Session");
        btnViewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnViewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slecture, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stags, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sscode, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssubject, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dhrs, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nostudents, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchText)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(slecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sscode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ssubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dhrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nostudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed

        new AddSession().setVisible(true);
        this.setVisible(false);
        //    mng_std.setVisible(true);
        //  this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void combo1() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
            String sql = "select * from lecture";
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String n = rs.getString("name");
                slecture.addItem(n);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void combo2() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
            String sql = "select * from tags";
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String a = rs.getString("tagname");
                stags.addItem(a);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void combo3() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
            String sql = "select * from subject";
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String b = rs.getString("code");
                sscode.addItem(b);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void combo4() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
            String sql = "select * from subject";
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String c = rs.getString("name");
                ssubject.addItem(c);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void combo5() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
            String sql = "select * from students";
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String d = rs.getString("subGroupId");
                sgroup.addItem(d);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void nostudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nostudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nostudentsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "DELETE FROM session WHERE lname = ?";
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
                    ps=con.prepareStatement(sql);
               
                    ps.setString(1,slecture.getSelectedItem().toString());
                    
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Delete Succesfully");
                    
                    showTable3();
        }
        catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
                    
                    
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
                    String sql = "UPDATE session SET tag=?, scode=?, sub_ject=?, gro_up=?, duration=?, noofstd=? WHERE lname =?";
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
                    ps=con.prepareStatement(sql);
                    
                    
                    ps.setString(7,slecture.getSelectedItem().toString());                    
                    ps.setString(1,stags.getSelectedItem().toString());
                    ps.setString(2,sscode.getSelectedItem().toString());
                    ps.setString(3,ssubject.getSelectedItem().toString());
                    ps.setString(4,sgroup.getSelectedItem().toString());
                    ps.setString(5,dhrs.getText());
                    ps.setString(6,nostudents.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Updated Succesfully");
                    
                    showTable3();
                    
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
                    
                    
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void sessionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sessionTableMouseClicked
        // TODO add your handling code here:
        int r = sessionTable.getSelectedRow();
        
        
        String b = sessionTable.getValueAt(r, 1).toString();
        String c = sessionTable.getValueAt(r, 2).toString();
        String d = sessionTable.getValueAt(r, 3).toString();
        String e = sessionTable.getValueAt(r, 4).toString();
        String f = sessionTable.getValueAt(r, 5).toString();
        String g = sessionTable.getValueAt(r, 6).toString();
        String h = sessionTable.getValueAt(r, 7).toString();
        
        slecture.addItem(sessionTable.getValueAt(r,1).toString());
        stags.addItem(sessionTable.getValueAt(r,2).toString());
        sscode.addItem(sessionTable.getValueAt(r,3).toString());
        ssubject.addItem(sessionTable.getValueAt(r,4).toString());
        sgroup.addItem(sessionTable.getValueAt(r,5).toString());
        
        slecture.setSelectedItem(b);
        stags.setSelectedItem(c);
        sscode.setSelectedItem(d);
        ssubject.setSelectedItem(e);
        sgroup.setSelectedItem(f);
        dhrs.setText(g);
        nostudents.setText(h);
    }//GEN-LAST:event_sessionTableMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnViewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSessionActionPerformed
        // TODO add your handling code here:
       String a1, a2, a3, a4, a5, a6, a7, a8,result;
       
        a1 = (String)slecture.getSelectedItem();
        a2 = (String)stags.getSelectedItem();
        a3 = (String)sscode.getSelectedItem();
        a4 = (String)ssubject.getSelectedItem();
        a5 = (String)sgroup.getSelectedItem();
        a6 = (String)dhrs.getText();
        a7 = (String)nostudents.getText();
        a8 = "-";
        
        result = a1+a8+a2+a8+a3+a8+a4+a8+a5+a8+a6+a8+a7;
        
        JOptionPane.showMessageDialog(null, "Session is "+result);
        
    }//GEN-LAST:event_btnViewSessionActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select * from session where lname =?" ;
            
            ps = con.prepareStatement(sql);
            ps.setString(1, searchText.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                String add1 = rs.getString("lname");
                slecture.setSelectedItem(add1);
                String add2 = rs.getString("tag");
                stags.setSelectedItem(add2);
                String add3 = rs.getString("scode");
                sscode.setSelectedItem(add3);
                String add4 = rs.getString("sub_ject");
                ssubject.setSelectedItem(add4);
                String add5 = rs.getString("gro_up");
                sgroup.setSelectedItem(add5);
                String add6 = rs.getString("duration");
                dhrs.setText(add6);
                String add7 = rs.getString("noofstd");
                nostudents.setText(add7);
            }           
        }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    }
        
        try {
            String sql = "select * from session where tag =?" ;
            
            ps = con.prepareStatement(sql);
            ps.setString(1, searchText.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                String add1 = rs.getString("lname");
                slecture.setSelectedItem(add1);
                String add2 = rs.getString("tag");
                stags.setSelectedItem(add2);
                String add3 = rs.getString("scode");
                sscode.setSelectedItem(add3);
                String add4 = rs.getString("sub_ject");
                ssubject.setSelectedItem(add4);
                String add5 = rs.getString("gro_up");
                sgroup.setSelectedItem(add5);
                String add6 = rs.getString("duration");
                dhrs.setText(add6);
                String add7 = rs.getString("noofstd");
                nostudents.setText(add7);
            }           
        }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    }
        
        try {
            String sql = "select * from session where scode =?" ;
            
            ps = con.prepareStatement(sql);
            ps.setString(1, searchText.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                String add1 = rs.getString("lname");
                slecture.setSelectedItem(add1);
                String add2 = rs.getString("tag");
                stags.setSelectedItem(add2);
                String add3 = rs.getString("scode");
                sscode.setSelectedItem(add3);
                String add4 = rs.getString("sub_ject");
                ssubject.setSelectedItem(add4);
                String add5 = rs.getString("gro_up");
                sgroup.setSelectedItem(add5);
                String add6 = rs.getString("duration");
                dhrs.setText(add6);
                String add7 = rs.getString("noofstd");
                nostudents.setText(add7);
            }           
        }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    }
        
        try {
            String sql = "select * from session where sub_ject =?" ;
            
            ps = con.prepareStatement(sql);
            ps.setString(1, searchText.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                String add1 = rs.getString("lname");
                slecture.setSelectedItem(add1);
                String add2 = rs.getString("tag");
                stags.setSelectedItem(add2);
                String add3 = rs.getString("scode");
                sscode.setSelectedItem(add3);
                String add4 = rs.getString("sub_ject");
                ssubject.setSelectedItem(add4);
                String add5 = rs.getString("gro_up");
                sgroup.setSelectedItem(add5);
                String add6 = rs.getString("duration");
                dhrs.setText(add6);
                String add7 = rs.getString("noofstd");
                nostudents.setText(add7);
            }           
        }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    }
        
        try {
            String sql = "select * from session where gro_up =?" ;
            
            ps = con.prepareStatement(sql);
            ps.setString(1, searchText.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                String add1 = rs.getString("lname");
                slecture.setSelectedItem(add1);
                String add2 = rs.getString("tag");
                stags.setSelectedItem(add2);
                String add3 = rs.getString("scode");
                sscode.setSelectedItem(add3);
                String add4 = rs.getString("sub_ject");
                ssubject.setSelectedItem(add4);
                String add5 = rs.getString("gro_up");
                sgroup.setSelectedItem(add5);
                String add6 = rs.getString("duration");
                dhrs.setText(add6);
                String add7 = rs.getString("noofstd");
                nostudents.setText(add7);
            }           
        }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    }
    }//GEN-LAST:event_btnSearchActionPerformed

    
    private void slectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slectureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slectureActionPerformed

    private void clear() {
        slecture.setSelectedIndex(0);
        stags.setSelectedIndex(0);
        sscode.setSelectedIndex(0);
        ssubject.setSelectedIndex(0);
        sgroup.setSelectedIndex(0);
        dhrs.setText("");
        nostudents.setText("");
    }
    public void showTable3(){
        try {                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/time_table_generator","root","1234");
                    String sql = "SELECT * FROM session";
                    ps=con.prepareStatement(sql);
                    
                    rs = ps.executeQuery();
                    sessionTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
                    
                    
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome3;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewSession;
    private javax.swing.JTextField dhrs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nostudents;
    private javax.swing.JTextField searchText;
    private javax.swing.JTable sessionTable;
    private javax.swing.JComboBox<String> sgroup;
    private javax.swing.JComboBox<String> slecture;
    private javax.swing.JComboBox<String> sscode;
    private javax.swing.JComboBox<String> ssubject;
    private javax.swing.JComboBox<String> stags;
    // End of variables declaration//GEN-END:variables
}
